In [50]:
import requests
import pandas as pd
import numpy as np

# 1. Cabeçalho

In [51]:
url = 'https://www.fundsexplorer.com.br/ranking'

In [52]:
response = requests.get(url)
if response.status_code == 200:
    df = pd.read_html(response.content, encoding = 'UTF-8')[0]

In [53]:
df.sort_values('Códigodo fundo', inplace = True)

In [54]:
df

,Códigodo fundo,Setor,Preço Atual,Liquidez Diária,Dividendo,DividendYield,DY (3M)Acumulado,DY (6M)Acumulado,DY (12M)Acumulado,DY (3M)Média,...,PatrimônioLíq.,VPA,P/VPA,DYPatrimonial,VariaçãoPatrimonial,Rentab. Patr.no Período,Rentab. Patr.Acumulada,VacânciaFísica,VacânciaFinanceira,QuantidadeAtivos
135,ABCP11,Shoppings,"R$ 73,30",1327.0,"R$ 0,42","0,57%","2,02%","2,62%","5,49%","0,67%",...,"R$ 1.080.690.326,04","R$ 88,55",83.0,NaN,NaN,NaN,NaN,"8,40%",NaN,1
54,AFCR11,Híbrido,"R$ 105,54",2824.0,"R$ 1,08","1,02%","3,43%","6,24%","11,29%","1,14%",...,"R$ 140.621.755,76","R$ 102,10",103.0,NaN,NaN,NaN,NaN,NaN,NaN,0
237,AFHI11,Títulos e Val. Mob.,"R$ 93,60",5715.0,"R$ 1,00","1,05%","2,93%","0,00%","0,00%","0,98%",...,"R$ 172.876.618,28","R$ 96,70",97.0,NaN,NaN,NaN,NaN,NaN,NaN,0
247,AFOF11,Títulos e Val. Mob.,"R$ 89,29",1053.0,"R$ 0,67","0,73%","0,00%","0,00%","0,00%","0,00%",...,"R$ 67.805.605,75","R$ 98,10",91.0,NaN,NaN,NaN,NaN,NaN,NaN,0
115,AIEC11,Lajes Corporativas,"R$ 80,00",25917.0,"R$ 0,61","0,75%","2,15%","4,06%","0,00%","0,72%",...,"R$ 484.941.482,42","R$ 100,51",80.0,NaN,NaN,NaN,NaN,"0,00%",NaN,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44,XPML11,Shoppings,"R$ 101,75",25053.0,"R$ 0,60","0,60%","1,46%","2,13%","4,21%","0,49%",...,"R$ 1.902.325.463,75","R$ 104,48",97.0,NaN,NaN,NaN,NaN,"5,20%",NaN,13
123,XPPR11,Outros,"R$ 67,60",16632.0,"R$ 0,55","0,80%","2,30%","4,47%","8,89%","0,77%",...,"R$ 618.295.002,65","R$ 84,51",80.0,NaN,NaN,NaN,NaN,"49,00%",NaN,4
160,XPSF11,Outros,"R$ 82,20",10823.0,"R$ 0,70","0,83%","2,36%","4,82%","9,40%","0,79%",...,"R$ 394.215.820,81","R$ 91,04",90.0,NaN,NaN,NaN,NaN,NaN,NaN,0
2,XTED11,Lajes Corporativas,"R$ 6,78",596.0,"R$ 0,00","0,00%","0,00%","0,00%","0,00%","0,00%",...,"R$ 26.247.801,80","R$ 13,59",50.0,NaN,NaN,NaN,NaN,"0,00%","100,00%",1
98,YUFI11B,Residencial,NaN,NaN,"R$ 0,35","0,00%","0,00%","0,00%","0,00%","0,00%",...,"R$ 37.561.151,44","R$ 95,06",NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 249 entries, 135 to 98
Data columns (total 26 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Códigodo fundo           249 non-null    object
 1   Setor                    249 non-null    object
 2   Preço Atual              241 non-null    object
 3   Liquidez Diária          241 non-null    float64
 4   Dividendo                249 non-null    object
 5   DividendYield            238 non-null    object
 6   DY (3M)Acumulado         238 non-null    object
 7   DY (6M)Acumulado         238 non-null    object
 8   DY (12M)Acumulado        238 non-null    object
 9   DY (3M)Média             238 non-null    object
 10  DY (6M)Média             238 non-null    object
 11  DY (12M)Média            238 non-null    object
 12  DY Ano                   228 non-null    object
 13  Variação Preço           238 non-null    object
 14  Rentab.Período           238 non-null    object
 15  Rentab.Acumulada         238 non-null    object
 16  PatrimônioLíq.           249 non-null    object
 17  VPA                      249 non-null    object
 18  P/VPA                    241 non-null    float64
 19  DYPatrimonial            0 non-null      float64
 20  VariaçãoPatrimonial      0 non-null      float64
 21  Rentab. Patr.no Período  0 non-null      float64
 22  Rentab. Patr.Acumulada   0 non-null      float64
 23  VacânciaFísica           120 non-null    object
 24  VacânciaFinanceira       26 non-null     object
 25  QuantidadeAtivos         249 non-null    int64
dtypes: float64(6), int64(1), object(19)
memory usage: 52.5+ KB

In [56]:
df.describe(include = 'all')

,Códigodo fundo,Setor,Preço Atual,Liquidez Diária,Dividendo,DividendYield,DY (3M)Acumulado,DY (6M)Acumulado,DY (12M)Acumulado,DY (3M)Média,...,PatrimônioLíq.,VPA,P/VPA,DYPatrimonial,VariaçãoPatrimonial,Rentab. Patr.no Período,Rentab. Patr.Acumulada,VacânciaFísica,VacânciaFinanceira,QuantidadeAtivos
count,249,249,241,241.000000,249,238,238,238,238,238,...,249,249,241.000000,0.0,0.0,0.0,0.0,120,26,249.000000
unique,249,9,231,NaN,105,90,142,163,148,89,...,249,239,NaN,NaN,NaN,NaN,NaN,72,18,NaN
top,MCCI11,Títulos e Val. Mob.,"R$ 94,00",NaN,"R$ 0,00","0,00%","0,00%","0,00%","0,00%","0,00%",...,"R$ 814.503.427,59","R$ 95,44",NaN,NaN,NaN,NaN,NaN,"0,00%","0,00%",NaN
freq,1,76,3,NaN,14,19,25,40,79,25,...,1,2,NaN,NaN,NaN,NaN,NaN,40,9,NaN
mean,NaN,NaN,NaN,14433.838174,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,89.377593,NaN,NaN,NaN,NaN,NaN,NaN,3.445783
std,NaN,NaN,NaN,42338.517990,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,31.200470,NaN,NaN,NaN,NaN,NaN,NaN,8.051627
min,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,-131.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
25%,NaN,NaN,NaN,206.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
50%,NaN,NaN,NaN,2277.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,91.000000,NaN,NaN,NaN,NaN,NaN,NaN,1.000000
75%,NaN,NaN,NaN,11496.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,99.000000,NaN,NaN,NaN,NaN,NaN,NaN,3.000000
max,NaN,NaN,NaN,519229.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,396.000000,NaN,NaN,NaN,NaN,NaN,NaN,72.000000

In [57]:
df.Setor.unique()

array(['Shoppings', 'Híbrido', 'Títulos e Val. Mob.',
       'Lajes Corporativas', 'Logística', 'Outros', 'Residencial',
       'Hospital', 'Hotel'], dtype=object)

In [58]:
df.columns

Index(['Códigodo fundo', 'Setor', 'Preço Atual', 'Liquidez Diária',
       'Dividendo', 'DividendYield', 'DY (3M)Acumulado', 'DY (6M)Acumulado',
       'DY (12M)Acumulado', 'DY (3M)Média', 'DY (6M)Média', 'DY (12M)Média',
       'DY Ano', 'Variação Preço', 'Rentab.Período', 'Rentab.Acumulada',
       'PatrimônioLíq.', 'VPA', 'P/VPA', 'DYPatrimonial',
       'VariaçãoPatrimonial', 'Rentab. Patr.no Período',
       'Rentab. Patr.Acumulada', 'VacânciaFísica', 'VacânciaFinanceira',
       'QuantidadeAtivos'],
      dtype='object')

# 2. Limpeza

In [59]:
df.isna().sum()

Códigodo fundo               0
Setor                        0
Preço Atual                  8
Liquidez Diária              8
Dividendo                    0
DividendYield               11
DY (3M)Acumulado            11
DY (6M)Acumulado            11
DY (12M)Acumulado           11
DY (3M)Média                11
DY (6M)Média                11
DY (12M)Média               11
DY Ano                      21
Variação Preço              11
Rentab.Período              11
Rentab.Acumulada            11
PatrimônioLíq.               0
VPA                          0
P/VPA                        8
DYPatrimonial              249
VariaçãoPatrimonial        249
Rentab. Patr.no Período    249
Rentab. Patr.Acumulada     249
VacânciaFísica             129
VacânciaFinanceira         223
QuantidadeAtivos             0
dtype: int64

## Dados Categóricos

In [60]:
categorical_columns = ['Códigodo fundo', 'Setor']

In [61]:
idx = df[df.Setor.isna()].index
df.drop(idx, inplace = True)

In [62]:
df[categorical_columns] = df[categorical_columns].astype('category')

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 249 entries, 135 to 98
Data columns (total 26 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Códigodo fundo           249 non-null    category
 1   Setor                    249 non-null    category
 2   Preço Atual              241 non-null    object
 3   Liquidez Diária          241 non-null    float64
 4   Dividendo                249 non-null    object
 5   DividendYield            238 non-null    object
 6   DY (3M)Acumulado         238 non-null    object
 7   DY (6M)Acumulado         238 non-null    object
 8   DY (12M)Acumulado        238 non-null    object
 9   DY (3M)Média             238 non-null    object
 10  DY (6M)Média             238 non-null    object
 11  DY (12M)Média            238 non-null    object
 12  DY Ano                   228 non-null    object
 13  Variação Preço           238 non-null    object
 14  Rentab.Período           238 non-null    object
 15  Rentab.Acumulada         238 non-null    object
 16  PatrimônioLíq.           249 non-null    object
 17  VPA                      249 non-null    object
 18  P/VPA                    241 non-null    float64
 19  DYPatrimonial            0 non-null      float64
 20  VariaçãoPatrimonial      0 non-null      float64
 21  Rentab. Patr.no Período  0 non-null      float64
 22  Rentab. Patr.Acumulada   0 non-null      float64
 23  VacânciaFísica           120 non-null    object
 24  VacânciaFinanceira       26 non-null     object
 25  QuantidadeAtivos         249 non-null    int64
dtypes: category(2), float64(6), int64(1), object(17)
memory usage: 67.9+ KB

In [64]:
df.isna().sum()

Códigodo fundo               0
Setor                        0
Preço Atual                  8
Liquidez Diária              8
Dividendo                    0
DividendYield               11
DY (3M)Acumulado            11
DY (6M)Acumulado            11
DY (12M)Acumulado           11
DY (3M)Média                11
DY (6M)Média                11
DY (12M)Média               11
DY Ano                      21
Variação Preço              11
Rentab.Período              11
Rentab.Acumulada            11
PatrimônioLíq.               0
VPA                          0
P/VPA                        8
DYPatrimonial              249
VariaçãoPatrimonial        249
Rentab. Patr.no Período    249
Rentab. Patr.Acumulada     249
VacânciaFísica             129
VacânciaFinanceira         223
QuantidadeAtivos             0
dtype: int64

## Dados numéricos

In [65]:
col_floats = list(df.iloc[:, 2:-1].columns)

In [66]:
## Dados nulos
df[col_floats] = df[col_floats].fillna(value = 0)

In [67]:
df[col_floats] = df[col_floats].applymap(lambda x: str(x).replace('R$', '').replace('.0', '').replace('.', '').replace('%', '').replace(',', '.'))

In [68]:
df[col_floats] = df[col_floats].astype('float')

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 249 entries, 135 to 98
Data columns (total 26 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Códigodo fundo           249 non-null    category
 1   Setor                    249 non-null    category
 2   Preço Atual              249 non-null    float64
 3   Liquidez Diária          249 non-null    float64
 4   Dividendo                249 non-null    float64
 5   DividendYield            249 non-null    float64
 6   DY (3M)Acumulado         249 non-null    float64
 7   DY (6M)Acumulado         249 non-null    float64
 8   DY (12M)Acumulado        249 non-null    float64
 9   DY (3M)Média             249 non-null    float64
 10  DY (6M)Média             249 non-null    float64
 11  DY (12M)Média            249 non-null    float64
 12  DY Ano                   249 non-null    float64
 13  Variação Preço           249 non-null    float64
 14  Rentab.Período           249 non-null    float64
 15  Rentab.Acumulada         249 non-null    float64
 16  PatrimônioLíq.           249 non-null    float64
 17  VPA                      249 non-null    float64
 18  P/VPA                    249 non-null    float64
 19  DYPatrimonial            249 non-null    float64
 20  VariaçãoPatrimonial      249 non-null    float64
 21  Rentab. Patr.no Período  249 non-null    float64
 22  Rentab. Patr.Acumulada   249 non-null    float64
 23  VacânciaFísica           249 non-null    float64
 24  VacânciaFinanceira       249 non-null    float64
 25  QuantidadeAtivos         249 non-null    int64
dtypes: category(2), float64(23), int64(1)
memory usage: 67.9 KB

In [70]:
df.head()

,Códigodo fundo,Setor,Preço Atual,Liquidez Diária,Dividendo,DividendYield,DY (3M)Acumulado,DY (6M)Acumulado,DY (12M)Acumulado,DY (3M)Média,...,PatrimônioLíq.,VPA,P/VPA,DYPatrimonial,VariaçãoPatrimonial,Rentab. Patr.no Período,Rentab. Patr.Acumulada,VacânciaFísica,VacânciaFinanceira,QuantidadeAtivos
135,ABCP11,Shoppings,73.30,1327.0,0.42,0.57,2.02,2.62,5.49,0.67,...,1.806903e+08,88.55,83.0,0.0,0.0,0.0,0.0,8.4,0.0,1
54,AFCR11,Híbrido,105.54,2824.0,1.08,1.02,3.43,6.24,11.29,1.14,...,1.406218e+08,102.10,103.0,0.0,0.0,0.0,0.0,0.0,0.0,0
237,AFHI11,Títulos e Val. Mob.,93.60,5715.0,1.00,1.05,2.93,0.00,0.00,0.98,...,1.728766e+08,96.70,97.0,0.0,0.0,0.0,0.0,0.0,0.0,0
247,AFOF11,Títulos e Val. Mob.,89.29,1053.0,0.67,0.73,0.00,0.00,0.00,0.00,...,6.780561e+07,98.10,91.0,0.0,0.0,0.0,0.0,0.0,0.0,0
115,AIEC11,Lajes Corporativas,80.00,25917.0,0.61,0.75,2.15,4.06,0.00,0.72,...,4.849415e+08,100.51,80.0,0.0,0.0,0.0,0.0,0.0,0.0,2

In [71]:
df.describe()

,Preço Atual,Liquidez Diária,Dividendo,DividendYield,DY (3M)Acumulado,DY (6M)Acumulado,DY (12M)Acumulado,DY (3M)Média,DY (6M)Média,DY (12M)Média,...,PatrimônioLíq.,VPA,P/VPA,DYPatrimonial,VariaçãoPatrimonial,Rentab. Patr.no Período,Rentab. Patr.Acumulada,VacânciaFísica,VacânciaFinanceira,QuantidadeAtivos
count,249.000000,249.000000,249.000000,249.000000,249.000000,249.000000,249.000000,249.000000,249.000000,249.000000,...,2.490000e+02,249.000000,249.000000,249.0,249.0,249.0,249.0,249.000000,249.000000,249.000000
mean,417.297871,13970.100402,4.813976,0.774337,1.961847,3.352811,5.221365,0.654016,0.558956,0.435181,...,3.820819e+08,478.512249,86.506024,0.0,0.0,0.0,0.0,7.313414,1.330843,3.445783
std,4680.111892,41728.054049,58.033513,2.286697,2.516390,3.249572,5.248275,0.838521,0.541711,0.437400,...,5.985926e+08,4936.350835,34.517775,0.0,0.0,0.0,0.0,17.657940,8.339094,8.051627
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,-6.986891e+06,-9.210000,-131.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000
25%,72.630000,153.000000,0.450000,0.490000,1.380000,1.540000,0.000000,0.460000,0.260000,0.000000,...,4.992327e+07,91.040000,79.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000
50%,92.120000,2048.000000,0.640000,0.690000,1.970000,3.570000,5.880000,0.660000,0.590000,0.490000,...,1.636335e+08,98.880000,91.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,1.000000
75%,103.380000,10823.000000,0.900000,0.830000,2.480000,4.570000,8.300000,0.830000,0.760000,0.690000,...,3.942158e+08,109.550000,99.000000,0.0,0.0,0.0,0.0,5.000000,0.000000,3.000000
max,73900.000000,519229.000000,915.780000,36.320000,37.990000,40.960000,45.220000,12.660000,6.830000,3.770000,...,3.884535e+09,77824.110000,396.000000,0.0,0.0,0.0,0.0,100.000000,100.000000,72.000000

* Dados de P/VPA tem atributos infinitos e está em uma escala diferente

In [72]:
## Check infinity values pandas
df[np.isinf(df[col_floats]).any(1)]

Empty DataFrame
Columns: [Códigodo fundo, Setor, Preço Atual, Liquidez Diária, Dividendo, DividendYield, DY (3M)Acumulado, DY (6M)Acumulado, DY (12M)Acumulado, DY (3M)Média, DY (6M)Média, DY (12M)Média, DY Ano, Variação Preço, Rentab.Período, Rentab.Acumulada, PatrimônioLíq., VPA, P/VPA, DYPatrimonial, VariaçãoPatrimonial, Rentab. Patr.no Período, Rentab. Patr.Acumulada, VacânciaFísica, VacânciaFinanceira, QuantidadeAtivos]
Index: []

[0 rows x 26 columns]

In [73]:
idx = df[np.isinf(df[col_floats]).any(1)].index
df.drop(idx, inplace = True)

In [76]:
df['P/VPA'] = df ['P/VPA'] / 100

In [77]:
df.describe()

,Preço Atual,Liquidez Diária,Dividendo,DividendYield,DY (3M)Acumulado,DY (6M)Acumulado,DY (12M)Acumulado,DY (3M)Média,DY (6M)Média,DY (12M)Média,...,PatrimônioLíq.,VPA,P/VPA,DYPatrimonial,VariaçãoPatrimonial,Rentab. Patr.no Período,Rentab. Patr.Acumulada,VacânciaFísica,VacânciaFinanceira,QuantidadeAtivos
count,249.000000,249.000000,249.000000,249.000000,249.000000,249.000000,249.000000,249.000000,249.000000,249.000000,...,2.490000e+02,249.000000,249.000000,249.0,249.0,249.0,249.0,249.000000,249.000000,249.000000
mean,417.297871,13970.100402,4.813976,0.774337,1.961847,3.352811,5.221365,0.654016,0.558956,0.435181,...,3.820819e+08,478.512249,0.000865,0.0,0.0,0.0,0.0,7.313414,1.330843,3.445783
std,4680.111892,41728.054049,58.033513,2.286697,2.516390,3.249572,5.248275,0.838521,0.541711,0.437400,...,5.985926e+08,4936.350835,0.000345,0.0,0.0,0.0,0.0,17.657940,8.339094,8.051627
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,-6.986891e+06,-9.210000,-0.001310,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000
25%,72.630000,153.000000,0.450000,0.490000,1.380000,1.540000,0.000000,0.460000,0.260000,0.000000,...,4.992327e+07,91.040000,0.000790,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000
50%,92.120000,2048.000000,0.640000,0.690000,1.970000,3.570000,5.880000,0.660000,0.590000,0.490000,...,1.636335e+08,98.880000,0.000910,0.0,0.0,0.0,0.0,0.000000,0.000000,1.000000
75%,103.380000,10823.000000,0.900000,0.830000,2.480000,4.570000,8.300000,0.830000,0.760000,0.690000,...,3.942158e+08,109.550000,0.000990,0.0,0.0,0.0,0.0,5.000000,0.000000,3.000000
max,73900.000000,519229.000000,915.780000,36.320000,37.990000,40.960000,45.220000,12.660000,6.830000,3.770000,...,3.884535e+09,77824.110000,0.003960,0.0,0.0,0.0,0.0,100.000000,100.000000,72.000000

## Analisando a média por setor

In [78]:
df.columns

Index(['Códigodo fundo', 'Setor', 'Preço Atual', 'Liquidez Diária',
       'Dividendo', 'DividendYield', 'DY (3M)Acumulado', 'DY (6M)Acumulado',
       'DY (12M)Acumulado', 'DY (3M)Média', 'DY (6M)Média', 'DY (12M)Média',
       'DY Ano', 'Variação Preço', 'Rentab.Período', 'Rentab.Acumulada',
       'PatrimônioLíq.', 'VPA', 'P/VPA', 'DYPatrimonial',
       'VariaçãoPatrimonial', 'Rentab. Patr.no Período',
       'Rentab. Patr.Acumulada', 'VacânciaFísica', 'VacânciaFinanceira',
       'QuantidadeAtivos'],
      dtype='object')

In [79]:
indicadores = [
    'Códigodo fundo',
    'Setor',
    'DY (12M)Acumulado',
    'VacânciaFísica',
    'VacânciaFinanceira',
    'P/VPA',
    'QuantidadeAtivos',
    'Liquidez Diária'
]

In [80]:
df_aux = df[indicadores]

In [82]:
media_setor = df_aux.groupby('Setor').agg(['mean', 'std'])

In [83]:
media_setor.loc['Residencial', ('DY (12M)Acumulado', 'mean')]

5.122

## Criando uma função com uma estratégia para oportunidades do mercado

In [89]:
def oportunidade_media_setor(df, setor = 'Shoppings', label_setor = 'Setor'):
    
    media_setor = df_aux.groupby('Setor').agg(['mean', 'std'])
    
    df_setor = df[df[label_setor].isin([setor])]
    
    filter_ = \
            (df_setor['QuantidadeAtivos'] > 5) &\
            (df_setor['Liquidez Diária'] > 500) &\
            (df_setor['P/VPA'] < 1.0) &\
            (df_setor['DY (12M)Acumulado'] > media_setor.loc[setor, ('DY (12M)Acumulado', 'mean')])
    
    print('A média do setor Yield: {}'.format(media_setor.loc[setor, ('DY (12M)Acumulado', 'mean')]))
    print('A média do setor p/VPA: {}'.format(media_setor.loc[setor, ('P/VPA', 'mean')]))
    print('A média do setor Ativos: {}'.format(media_setor.loc[setor, ('QuantidadeAtivos', 'mean')]))
    
    return df_setor[filter_]

In [90]:
list(df.Setor.unique())

['Shoppings',
 'Híbrido',
 'Títulos e Val. Mob.',
 'Lajes Corporativas',
 'Logística',
 'Outros',
 'Residencial',
 'Hospital',
 'Hotel']

In [91]:
oportunidade = oportunidade_media_setor(df_aux, setor = 'Shoppings')
oportunidade.sort_values('DY (12M)Acumulado', ascending = False, inplace = True)
oportunidade

A média do setor Yield: 2.635909090909091
A média do setor p/VPA: 0.0007386363636363636
A média do setor Ativos: 4.2727272727272725

,Códigodo fundo,Setor,DY (12M)Acumulado,VacânciaFísica,VacânciaFinanceira,P/VPA,QuantidadeAtivos,Liquidez Diária
53,MALL11,Shoppings,6.26,3.0,0.0,0.00091,7,8887.0
150,VISC11,Shoppings,4.47,8.3,0.0,0.00085,15,22399.0
44,XPML11,Shoppings,4.21,5.2,0.0,0.00097,13,25053.0
63,HGBS11,Shoppings,3.22,8.0,0.0,0.00089,17,3233.0

As métricas são aleatórias, apenas para teste...